services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./app"
        target: "/app"
    ports:
      - 8080:80
    command: uvicorn main:app --host 0.0.0.0 --port 80
