[tool.black]
line-length = 119
target-version = ['py311']
include = '\.py$'

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
show_error_codes = true
warn_unreachable = true
strict_optional = true
